# Generated by Django 4.2 on 2025-04-18 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cart_created_at'),
        ('subbranch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbranch',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='subbranch',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='store.orderitem'),
        ),
    ]
