# Generated by Django 4.2 on 2025-04-21 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subbranch', '0003_subbranch_email_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbranch',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subbranch',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subbranch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
    ]
