# Generated by Django 4.2 on 2025-04-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subbranch', '0004_subbranch_password_alter_subbranch_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subbranch',
            name='password',
        ),
    ]
